version: "3.8"

services:
  postgres:
    image: postgres:14
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ./packages/backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - ./packages/backend:/app
      - /app/node_modules

volumes:
  postgres_data: